"""Factory functions for pre-configured httpx async clients."""

from __future__ import annotations

import httpx

from src.opsec.fingerprint import generate_headers
from src.opsec.proxy_manager import proxy_manager


def create_httpx_client(stealth: bool = True, timeout: int = 30) -> httpx.AsyncClient:
    """Return an ``httpx.AsyncClient`` routed through the active proxy.

    When *stealth* is ``True`` the client is configured with randomised
    browser-like headers generated by :func:`generate_headers`.
    """

    proxy_config = proxy_manager.get_httpx_proxy_config()
    headers = generate_headers() if stealth else {}

    return httpx.AsyncClient(
        headers=headers,
        timeout=timeout,
        follow_redirects=True,
        **proxy_config,
    )


def create_direct_client(timeout: int = 30) -> httpx.AsyncClient:
    """Return a plain ``httpx.AsyncClient`` with no proxy and no stealth
    headers.  Useful for querying local services or trusted APIs."""

    return httpx.AsyncClient(
        timeout=timeout,
        follow_redirects=True,
    )
